### ISSUE TITLE
Fix the auto-scroll down.

### ISSUE THREAD

**Issue by MichaelWDanko** [MichaelWDanko/day18_ModifiedChatApp#7]

**Comment by DeemsW** [comment]
This was the code that worked for me in my chat app:

var scrollControl = document.getElementById("style");
            scrollControl.scrollTop = scrollControl.scrollHeight;

where "style" was the id attached to the actual scrolling element itself, not the whole scroll bar.

**Comment by MichaelWDanko** [comment]
@DeemsW I have tried something similar. In fact, it was the same exact code. I just can't seem to get it to work for some reason. I think when we finish, we will have to go through and clear any reference of it and try to do it again

**Comment by DeemsW** [comment]
got this working. if no conflicts, we can close this issue
