### ISSUE TITLE
Fix the clearing of username field when refresh happens.

### ISSUE THREAD

**Issue by MichaelWDanko** [MichaelWDanko/day18_ModifiedChatApp#8]

**Comment by DeemsW** [comment]
This was the code I used to clear the input boxes upon refresh. I'd think simply deleting the top (var = nullName) line of code would achieve your goal if you implemented it this way or some similar way in the first place.

var nullName = document.getElementById('username');
        nullName.value = '';
var nullMessage = document.getElementById('message');
        nullMessage.value = '';
